name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "wrfo8v74tj6oqof2v7q94iyx"
  title = "Relire le projet"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "f1334zmuc4rfn9srccbv20fc"
  title = "Définition des rôles"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "buyi45a4s8n28aj41oyxtu58"
name = "In Progress"

  [[processes.tasks]]
  id = "irz7mgt6yy7whwkl72j94k1n"
  title = "Installation x3270 anouar | sylvain"
  description = "<p></p>"
  tag = ""
  linkFiles = [ ]
  dueDate = "2025-08-06T22:00:00.000Z"
  priority = "High"
  linkCommits = [ ]

    [[processes.tasks.checkList]]
    id = "ginmwnis6p27xomy9tuuk4ab"
    title = "github / VScode"
    completed = false

    [[processes.tasks.checkList]]
    id = "l6ton0klom5w8k1drpkak8t5"
    title = "x3270"
    completed = false

[[processes]]
id = "process3"
name = "Done"
tasks = [ ]
